<a href="https://colab.research.google.com/github/kyjness/Undergraduate-Research-Assistant/blob/main/%ED%95%99%EB%B6%80%EC%97%B0%EA%B5%AC%EC%83%9D_1%EC%A3%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Python**

##7.객체지향

###7,1 클래스(class)와 인스턴스

In [ ]:
class Singer:
  def sing(self):
    return 'Lalala~'

taeji = Singer()
taeji.sing()

'Lalala~'

In [ ]:
ricky = Singer()
ricky.sing()

'Lalala~'

###7.2 변수와 메서드

In [ ]:
class Amazon:
  strength = 20
  dexterity = 25
  vitality = 20
  energy = 15

  def attack(self):
    return 'Jab!!!'

In [ ]:
#두 명의 여전사 탄생
import diablo2
jane = diablo2.Amazon()
mary = diablo2.Amazon()

ModuleNotFoundError: No module named 'diablo2'

###7.3 상속

In [ ]:
class Person:
  eyes = 2
  nose = 1
  mouth = 1
  ears = 2
  arms = 2
  legs = 2

  def eat(self):
    print('암냠...')
  def sleep(self):
    print('쿨쿨...')
  def talk(self):
    print('주절주절...')

In [ ]:
#Person 클래스를 상속받음
class Student(Person):
  def study(self):
    print('열공열공...')

In [ ]:
lee = Person()
lee.mouth

1

In [ ]:
lee.talk()

주절주절...


In [ ]:
kim = Student()
kim.mouth

1

In [ ]:
kim.talk()

주절주절...


In [ ]:
kim.study()

열공열공...


###7.4 객체 속의 객체

In [ ]:
%%writefile fridge.py
class Fridge:
  def __init__(self):
    self.isOpened = False
    self.foods = []

  def open(self):
    self.isOpened = True
    print('냉장고 문을 열었어요....')

  def put(self, thing):
    if self.isOpened:
      self.foods.append(thing)
      print('냉장고 속에 음식이 들어갔네...')
    else:
      print('냉장고 문이 닫혀있어서 못넣겠어요....')

    def close(self):
      self.isOpened = False
      print('냉장고 문을 닫았어요....')

class Food:
  pass

Overwriting fridge.py


In [ ]:
import fridge
f = fridge.Fridge()
apple = fridge.Food()
elephant = fridge.Food()

In [ ]:
f.open()

냉장고 문을 열었어요....


In [ ]:
f.put(apple)

AttributeError: 'Fridge' object has no attribute 'foods'

###7.5 특별한 메서드들

In [ ]:
%%writefile bookstore.py
class Book:

  def setData(self, title, price, author):
    self.title = title
    self.price = price
    self.author = author

  def printData(self):
    print('제목 : ', self.title)
    print('가격 : ', self.price)
    print('저자 : ', self.author)

  def __init__(self):
    print('책 객체를 새로 만들었어요~')


Overwriting bookstore.py


In [ ]:
import bookstore
b = bookstore.Book()

책 객체를 새로 만들었어요~


In [ ]:
b.setData('누가 내 치즈를 먹었을까', '300원', '미키')
b.printData()

TypeError: cannot set 'title' attribute of immutable type 'set'

##8. 예외

###8.1 예외처리(try, except)**굵은 텍스트**

In [ ]:
print 방가~

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (<ipython-input-56-aabcc57e5290>, line 1)

In [ ]:
def f(a,b):
  if a and b: #a와 b가 둘 다 0이 아닐 때
    return (a * b) + (a / b)
  elif a: #그렇지 않고 a만 0이 아닐 때
    return '불능'
  else:  #a가 0일 때
    return '부정'

In [ ]:
f(3,0)

'불능'

In [ ]:
f(0,0)

'부정'

In [ ]:
f(0,3)

'부정'

In [ ]:
f(3000, 5000)

15000000.6

In [ ]:
def f(a,b):
  try:
    if a and b:
      return (a * b) + (a / b)
    elif a:
      return '불능'
    else:
      return '부정'
  except:  #에러가 발생했을 때
    print('똑 바로 살아라')

In [ ]:
f(0,0)

'부정'

##9.테스팅과 성능

###9.1 테스팅

In [ ]:
#주어진 연도가 윤년인지 아닌지를 반환하는 함수
def is_leap_year(year):
  if year % 4 != 0:
    return False
  elif year %100 != 0:
    return True
  elif year % 400 != 0:
    return False
  else:
    return True


In [ ]:
is_leap_year(2020)

True

In [ ]:
is_leap_year(2077)

False

#Numpy

##넘파이 ndarry 개요

In [ ]:
import numpy as np

#array()
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [ ]:
#ndim()
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


##ndarray의 데이터 타입

In [ ]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [ ]:
#int와 string이 섞여있는 경우
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype) #유니코드 문자열 값으로 변환

['1' '2' 'test'] <U21


In [ ]:
#int와 float이 섞여있는 경우
list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype) #float으로 변환

[1. 2. 3.] float64


In [ ]:
#int를 float64로 변환
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

#float64를 int32로 변환
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

#float을 in32로 변환
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


##ndarray를 편리하게 생성하기 - arrange, zeros, ones

In [ ]:
#arrange()
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape, sequence_array.ndim)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,) 1


In [ ]:
#zeros(): 모든값을 0으로 채움
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape, zero_array.ndim)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2) 2


In [ ]:
#ones(): 모든값을 1로 채움
one_array = np.ones((3,2)) #dtype을 정해주지 않으면 float64형태로 ndarray를 채움
print(one_array)
print(one_array.dtype, one_array.shape, one_array.ndim)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2) 2


##ndarray의 차원과 크기를 변경하는 reshape()

In [ ]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
array1.reshape(4,3) #지정된 사이즈로 변경이 불가능하면 오류가 뜸

ValueError: cannot reshape array of size 10 into shape (4,3)

In [ ]:
#'-1'적용
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5) #열에 5개 고정하고 2차원으로 바꾸라는 뜻
print(array2)
print('array2 shape:', array2.shape)
array3 = array1.reshape(5,-1) #행에 5개 고정하고 2차원으로 바꾸라는 뜻
print(array3)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
array2 shape: (2, 5)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array3 shape: (5, 2)


In [ ]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4) #지정된 사이즈로 변경이 불가능하면 오류가 뜸

ValueError: cannot reshape array of size 10 into shape (4)

In [ ]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))#1차원에서 +2해서 3차원으로 바꾸고 행,열 2X2라는 뜻
print(array3d)
print('array3d:\n', array3d.tolist()) #list로 변환
print('array3d shape:', array3d.shape)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array3d shape: (2, 2, 2)


In [ ]:
#3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print(array5)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)


In [ ]:
#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [ ]:
#다차원 reshape 예시
array24 = np.arange(24)
array7 = array24.reshape(2,4,3) #1차원에서 +2해서 3차원으로 만들고 행X열이 4X3이 되도록
print(array7)
print('array7:\n', array7.tolist())
print('array7 shape:', array7.shape)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
array7:
 [[[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]], [[12, 13, 14], [15, 16, 17], [18, 19, 20], [21, 22, 23]]]
array7 shape: (2, 4, 3)


##넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(indexing)

단일 값 추출

In [ ]:
#1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10) #stop보다 -1전에 끝남
print('array1:', array1)

array1: [1 2 3 4 5 6 7 8 9]


In [ ]:
#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))

value: 3
<class 'numpy.int64'>


In [ ]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [ ]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [ ]:
#1차원 ndarray 를 2차원의 3X3 ndarray로 변환후 [row,col] cnffur
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


슬라이싱

In [ ]:
#끝 바로 전 index까지 표현됨
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))
print(array3.ndim)

[1 2 3]
<class 'numpy.ndarray'>
1


In [ ]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d, '\n')

print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('array2d[1:3, :]\n', array2d[1:3, :])
print('array2d[:, :]\n', array2d[:, :])
print('array2d[:2, 1:]\n', array2d[:2, 1:],'\n')

print('array2d[:2, 0]\n', array2d[:2, 0])
array20 = array2d[:2,0]
print(array20.ndim) #로우나 컬럼 한쪽에만 슬라이싱을 적용하고, 다른 쪽 축에는 단일 값 인덱스를 적용, 그러면 1차원이 됨

array21 = array2d[0,:2]
print('array2d[0,:2]:\n', array2d[0,:2])
print(array21.ndim)

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]] 

array2d[:2, 0]
 [1 4]
1
array2d[0,:2]:
 [1 2]
1


In [ ]:
#2차원 ndarray 뒤에 오는 인덱스를 없애면 로우 축(axis 0)의 해당 로우 ndarray를 반환 & 1차원이 됨(3차원 ndarray 뒤에 오는 인덱스를 없애면 2차워 ndarray를 반환)
print(array2d[0])
print('array2d[0] shape:', array2d[0].shape, '\n')

print(array2d[1])
print('array2d[1] shape:', array2d[1].shape)

[1 2 3]
array2d[0] shape: (3,) 

[4 5 6]
array2d[1] shape: (3,)


펜시 인덱싱

In [ ]:
#슬라이싱이 아니라 리스트가 오면 해당 ndarray를 반환
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3,3)
print(array2d,'\n')

array3 = array2d[[0,1],2]
print('array2d[[0,1],2] => ', array3.tolist())

array4 = array2d[[0,1],0:2]
print('array2d[[0,1],0:2] => ', array4.tolist())

array5 = array2d[[0,2]]
print('array2d[[0,2]] => ', array5.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

array2d[[0,1],2] =>  [3, 6]
array2d[[0,1],0:2] =>  [[1, 2], [4, 5]]
array2d[[0,2]] =>  [[1, 2, 3], [7, 8, 9]]


불린 인덱싱

In [ ]:
array1d = np.arange(start = 1, stop = 10)
print(array1d)

#[]안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

[1 2 3 4 5 6 7 8 9]
array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [ ]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [ ]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


##행렬의 정렬 - sort()와 argsort()

행렬 정렬 - sort()

In [ ]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

#np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array) #np.sort()를 해도 원본은 바뀌지 않음

#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array) #ndarray.sort()는 원본 행렬 자체를 정렬

#np.sort()나 ndarray.sort()모두 오름차순으로 행렬 내 원소 정렬

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [ ]:
#내림차순
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [ ]:
array2d = np.array([[8,12],
                    [7,1]])
print(array2d,'\n')

#로우 방향으로 정렬
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

#칼럼 방향으로 정렬
sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

[[ 8 12]
 [ 7  1]] 

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


정렬된 행렬의 인덱스를 반환하기 - argsort()

In [ ]:
#argsort()는 원본 행렬을 오름차순으로 바꾼 후 원본 인덱스를 반환함, 리스트로 출력됨..!
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print('원본 행렬:',org_array)
print('원본 인덱스:', np.arange(org_array.size),'\n')
print('오름차순 된 행렬:',np.sort(org_array))
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

원본 행렬: [3 1 9 5]
원본 인덱스: [0 1 2 3] 

오름차순 된 행렬: [1 3 5 9]
<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [ ]:
#내림차순 원본 행렬 인덱스
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('내림차순으로 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

내림차순으로 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [ ]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


##선형대수 연산 - 행렬 내적과 전치 행렬 구하기

행렬 내적(행렬 곱) - dot()

In [ ]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])

dot_product = np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


전치 행렬 - transpose()

: 행과 열 위치를 교환한 원소로 구성한 행렬

In [ ]:
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]


#금융 데이터 분석을 위한 파이썬 판다스

##넘파이

###브로드캐스팅

In [ ]:
high = [92700, 92400, 92100, 94300, 92300]
low = [90000, 91100, 91700, 92100, 90900]

arr_high = np.array(high)
arr_low = np.array(low)

arr_diff = arr_high - arr_low
print(arr_diff)

[2700 1300  400 2200 1400]


In [ ]:
arr_high_x3 = arr_high * 3
arr_low_x2 = arr_low * 2
print(arr_high_x3 + arr_low_x2)

[458100 459400 459700 467100 458700]


In [ ]:
avg = (arr_high * 3) + (arr_low * 2)

data = [
    [92700, 92400, 92100, 94300, 92300],
    [90000, 91100, 91700, 92100, 90900]
]
arr = np.array(data)
print(arr)

[[92700 92400 92100 94300 92300]
 [90000 91100 91700 92100 90900]]


In [ ]:
print(arr[0] * 3 + arr[1]  * 2)

[458100 459400 459700 467100 458700]


In [ ]:
weight = np.array( [ 3, 2 ] ).reshape(2, 1)
print(weight)
print((weight * arr).sum(axis=0))

[[3]
 [2]]
[458100 459400 459700 467100 458700]


###조건 연산

In [ ]:
arr = np.array([10, 20, 30])
print(arr > 10)

[False  True  True]


In [ ]:
arr = np.array([10, 20, 30])
cond = [False, True, True]
print(arr[ cond ])

[20 30]


In [ ]:
arr = np.array([10, 20, 30])
print(arr[[False, True, True]])

[20 30]


In [ ]:
arr = np.array([10, 20, 30])
cond = arr > 10
print(arr[ cond ])

[20 30]


In [ ]:
print(arr[ arr > 10 ])

[20 30]


In [ ]:
cond.all()

False

In [ ]:
cond.any()

True

In [ ]:
arr = np.array([10, 20, 30])
cond0 = arr > 10
cond1 = arr < 30
print(arr[ cond0 & cond1 ])

[20]


In [ ]:
arr = np.array([10, 20, 30])
print(arr[ (arr > 10) & (arr < 30) ])

[20]


In [ ]:
arr = np.array([10, 20, 30])
cond = arr > 10
print(cond)

arr[cond] = 1
arr[~cond] = 0
print(arr)

[False  True  True]
[0 1 1]


In [ ]:
arr = np.array([10, 20, 30])
arr = np.where( arr > 10, 1, 0) #참일 경우 1, 거짓일 경우 0
print(arr)

[0 1 1]


In [ ]:
arr = np.array([10, 20, 30])
cond = arr > 10
arr[cond] = arr[cond] + 10
arr[~cond] = arr[~cond] - 10
print(arr)

[ 0 30 40]


In [ ]:
arr = np.array([10, 20, 30])
arr = np.where( arr > 10, arr+10, arr-10)
print(arr)

[ 0 30 40]


In [ ]:
lge = np.array([93000, 82400, 99100, 81000, 72300])

result = lge[  lge <= 85000  ]
print(result)
print( len(result) )

[82400 81000 72300]
3


###함수와 메서드

In [ ]:
arr = np.arange(8).reshape(4, 2)
print(arr)
print(arr.sum())

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
28


In [ ]:
print(arr.sum(axis=0))
print(arr.sum(axis=1))

[12 16]
[ 1  5  9 13]


In [ ]:
np.random.randint(3) #0부터 2까지 범위에서 임의의 숫자 하나를 선택

0

In [ ]:
print(np.random.randint(46, size=5))

[ 9 21 11 25 16]


In [ ]:
print(np.random.randint(46, size=(2, 5)))

[[ 2  9 27 12 43]
 [32 10  3  8 33]]


In [ ]:
#linespace
x = np.linspace(0, 10, 3) #0부터 10까지의 구간을 균등한 3개의 지점으로 분할하라는 의미
print(x)

[ 0.  5. 10.]


In [ ]:
#vstack
a = np.arange(4)
b = np.arange(4, 8)
c = np.vstack( [a, b])
print(c)

[[0 1 2 3]
 [4 5 6 7]]
